version: '3'

services:
  teste-postgres-compose:
    image: postgres
    container_name: postgresheroku
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mussum
      - POSTGRES_PASSWORD=docker
    ports:
      - 5433:5432
      